- src/OpenTok/Util/Client.php
```
Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "getBody" from namespace "OpenTok\Util".
```
> Fix UndefinedFunctionException: Attempted to call function getBody

- sample/Archiving/web/js/participant.js
This was preventing multiple participants from being able to connect properly. Variable error was written as err.
> Fixed Variable Name

- src/OpenTok/Archive.php
- src/OpenTok/OpenTok.php
- src/OpenTok/Util/Validators.php
- tests/OpenTok/ArchiveTest.php
- tests/OpenTok/OpenTokTest.php
- tests/mock/v2/project/APIKEY/archive/session_resolution-hd
- tests/mock/v2/project/APIKEY/archive/session_resolution-sd
**What is this PR doing?**
Adds the `resolution` parameter for the `startArchive` function and allows developer to get the `resolution` information from an archive.
**How should this be manually tested?**
Clone this locally and start an archive with the `resolution` set to either `640x480` or `1280x720`.
> add resolution parameter for archiving

- README.md
The force disconnect functionality already exists, but is not documented on the README.
> add force disconnect to readme

- src/OpenTok/Broadcast.php
- src/OpenTok/OpenTok.php
- src/OpenTok/Util/Client.php
Hi,  
When using the `startBroadcast` function, options are not taken into account because of this line :   
`$options = array_merge($defaults, array_intersect_key($options, $defaults));`  
which only take default var (layout).  
The idea is to create a broadcast with these parameters : 
```
$options = [
'layout' => Layout::getPIP(),
'maxDuration' => 10800, //3 hours
'resolution' => '1280x720',
'outputs' => [
'rtmp' => [
...
]
]
];
```
"maxDuration" and "resolution" are new parameters from this documentation page :   
https://tokbox.com/developer/rest/#start_broadcast
> Send options like maxDuration and resolution to startBroadcast

- .travis.yml
Facebook will not support PHP syntax any higher than 5.6 as they focus on hacklang, so removing support for this in our SDK. 
This is also blocking new PRs coming through, and will impact future work as we update the SDK, so we need to remove it before any major work starts.
> Removing HHVM support

- README.md
- src/OpenTok/OpenTok.php
- src/OpenTok/Util/Client.php
- src/OpenTok/Util/Validators.php
- tests/OpenTok/OpenTokTest.php
This allows a user to now pass a `timeout` option when creating the OpenTok client.
> Adds 'timeout' configuration option for OpenTok Client

- README.md
Have the example expose the fact `listArchives()` can take a session ID, so that way users aren't paging through all their archives.
> Add `$sessionId` parameter to `listArchives()` in README

- composer.json
Addressing issue #271, I have bumped the version of Guzzle to include ~7.0 to allow the SDK to be used with modern frameworks such as Laravel.
Locally I had three tests failing before making this change and the three same tests failed for the same reason after making the change so I don't believe the Guzzle version bump has caused the failing tests.
```
1) OpenTokTest::testSipCall
sizeof(): Parameter must be an array or an object that implements Countable
2) OpenTokTest::testSipCallWithAuth
sizeof(): Parameter must be an array or an object that implements Countable
3) OpenTokTest::testSipCallFrom
sizeof(): Parameter must be an array or an object that implements Countable
```
> Bumped Guzzle version to include ~7.0

- src/OpenTok/Exception/SignalNetworkConnectionException.php
- src/OpenTok/Util/Client.php
- tests/OpenTokTest/Utils/ClientTest.php
- tests/OpenTokTest/Utils/responses/signal-failure-invalid-token.json
- tests/OpenTokTest/Utils/responses/signal-failure-no-clients.json
- tests/OpenTokTest/Utils/responses/signal-failure-payload.json
- tests/OpenTokTest/Utils/responses/signal-failure.json
This adds some additional error handling and type checking around Signal responses. As a way to test, this also lets a custom Guzzle client be passed into the system via the options. This should fix #276 
Previously the SDK just checked for a generic `\Exception` being thrown, but then in the error handler was calling methods that exist only on certain Guzzle exceptions. This expands the exception handling to look for `GuzzleHttp\Exception\ClientException`, which was what the previous error handler expected, `GuzzleHttp\Exception\RequestException`, which seems to be the underlying cause of #276, and finally generic `\Exception`.
If a `RequestException` is encountered, we wrap that in a new `OpenTok\Exception\SignalNetworkConnectionException` so that client applications can now catch it. …
> Added more error handling around signal HTTP errors

- README.md
- src/OpenTok/Layout.php
- src/OpenTok/OpenTok.php
- src/OpenTok/Util/Client.php
- tests/OpenTokTest/LayoutTest.php
- tests/OpenTokTest/OpenTokTest.php
This adds the `screenshareType` key to the `\Opentok\Layout` class to support screenshare layouts. Users can now set a type on the layout objects directly with `setScreenshareType`.
This also includes cleanup around the methods that use the Layout features, as well as static typing for those methods.
The `screenshareType` option for layouts was added to the API, so this allows that functionality through the SDKs.
The other cleanups are general quality-of-life cleanups that are done on legacy code as we do maintenance.
Unit tests
```php
$layout = Layout::getBestFit();
$layout->setScreenshareLayout(Layout::LAYOUT_VERTICAL);
```
> Adding Screenshare Layout options

- src/OpenTok/OpenTok.php
"X-" prefix for custom headers no longer required
> Correction to SIP docs

- .gitignore
- DEVELOPING.md
- README.md
- phpdoc.dist.xml
- src/OpenTok/Archive.php
- src/OpenTok/ArchiveList.php
- src/OpenTok/Broadcast.php
- src/OpenTok/OpenTok.php
- src/OpenTok/Role.php
- src/OpenTok/Session.php
- src/OpenTok/StreamList.php
This updates the docs comments.
The docs were not building cleanly with PHP 8 and phpdoc 3.
Yes. Run php phpDocumentor.phar --config phpdoc.dist.xml.
- [ x] My code follows the code style of this project.
> Fix phpdoc

- src/OpenTok/Util/Client.php
This fixes a bug where the OpenTok client observeForceMute parameter was not carrying forward to the API Client class.
Added observeForceMute into the API client options payload.
Bug fix
Test suite passes
> Carry forward observeForceMute into the client

- src/OpenTok/Archive.php
- src/OpenTok/Broadcast.php
- src/OpenTok/OpenTok.php
- src/OpenTok/Util/Validators.php
- tests/OpenTokTest/Validators/ValidatorsTest.php
- tests/mock/v2/project/APIKEY/broadcast/BROADCASTID/get
- tests/mock/v2/project/APIKEY/broadcast/BROADCASTID/stop
The Archive and Broadcast API endpoints now support HD resolutions. This PR adds documentation to support these options and a new validator to throw exceptions when unsupported resolutions are given as arguments before they hit the API.
New tests added for the validation
> HD Resolutions for Broadcast / Archive

- composer.json
- sample/Archiving/templates/base.html
- sample/SipCall/templates/index.php
- src/OpenTok/Util/Client.php
- tests/OpenTokTest/TestHelpers.php
This PR directly to main takes care of several security issues raised by Github bots:
* Bootstrap update in sample app
* jQuery update in sample app
* Compser bump in PHP to get the latest firebase jwt library.
> fix: security bumps for composer firebase jwt and front end samples

- README.md
- src/OpenTok/OpenTok.php
- src/OpenTok/Util/Client.php
- src/OpenTok/Util/Validators.php
- tests/OpenTokTest/OpenTokTest.php
- tests/OpenTokTest/Util/ClientTest.php
- tests/OpenTokTest/Util/responses/connect.json
- tests/OpenTokTest/Validators/ValidatorsTest.php
- tests/mock/v2/project/APIKEY/connect
Add Audio Connector for the ability to add audio to Websockets
This PR adds a new method to the base Client, allowing for audio streams to be added to open websockets using the Audio Connector.
New feature as requested
Three new tests and a fixture to mock out behaviour
> Add Audio Connector for the ability to add audio to Websockets

- src/OpenTok/OpenTok.php
- src/OpenTok/Session.php
- tests/OpenTokTest/OpenTokTest.php
- tests/OpenTokTest/SessionTest.php
This PR adds the end to end encryption flag when starting an OpenTok Session.
See the docs for more context:
https://tokbox.com/developer/guides/end-to-end-encryption/
New features being rolled into our SDKs
Added new test and modified existing one to make sure defaults are read properly.
> Add end-to-end encryption when creating session.

- src/OpenTok/OpenTok.php
- src/OpenTok/Util/Client.php
- tests/OpenTokTest/ArchiveTest.php
- tests/OpenTokTest/OpenTokTest.php
This PR adds the ability for developers to create a new Client with a custom app name, to be included in the User-Agent string.
This has been requested to be rolled out across all of the SDKs for client tracking support.
Tests have been modified to pull out the original static string testing. As the string is dynamic, the new test for this is to only test the method that adds a custom app string to the Client.
> Custom User Agent

- .github/workflows/build.yml
Adding recent versions of PHP to build matrix
PHP 8.1 is out for 1.5 years, php 8.2 for half a year. Still they aren't part of the automatic test matrix
-
> Add php 8.1 and php 8.2 to github actions build matrix

- src/OpenTok/Util/Validators.php
- tests/OpenTokTest/LayoutTest.php
- tests/OpenTokTest/Validators/ValidatorsTest.php
Quick bugfix to either use PHP8.1 `array_is_list()` or fall back to correct logic.
> Fix Validator::isAssoc()

- src/OpenTok/Archive.php
- src/OpenTok/OpenTok.php
- tests/OpenTokTest/OpenTokTest.php
- tests/mock/v2/project/APIKEY/archive/ARCHIVEID/get
- tests/mock/v2/project/APIKEY/archive/session
This PR adds the ability to add a cap to the bitrate when starting an archive.
You can add maxBitrate within the `startArchive()` method when adding an options array.
```
$archive = $openTok->startArchive($sessionId, ['maxBitrate' => 2000000]);
```
Parity with Video APIs
StartArchive test has been modified.
> Added max bitrate and tests

- .github/workflows/build.yml
- composer.json
- sample/Archiving/README.md
- src/OpenTok/OpenTok.php
- src/OpenTok/Session.php
- tests/OpenTokTest/OpenTokTest.php
- tests/OpenTokTest/SessionTest.php
T1 tokens are being marked as legacy to increase security. Instead, SHA256 encoded JWTs will be used by default.
generateToken() now takes a default parameter that is set to true unless specifically set by the user. To use the old T1 tokens for backwards compatibility, set the parameters like so:
```
$client = new OpenTok\OpenTok();
$token = $client->generateToken(API_KEY, API_SECRET, [], true);
```
Increased security
Tests coming for the new tokens when exact setup of claims has been identified.
> Added legacy transformation, currently no tests for new JWT structure

- composer.json
- src/OpenTok/OpenTok.php
- tests/OpenTokTest/OpenTokTest.php
This PR replaces the JWT library with the Firebase JWT PHP Library.
JWTs are now created with Firebase JWT PHP library by default, and use the new SHA256 algorithm instead of the older T1 tokens used by TokBox.
Enhanced security.
> Use firebase JWT

- src/OpenTok/OpenTok.php
- src/OpenTok/Session.php
The docs implied that JWT tokens might not be backwards compatible. 
Clarifies the docs.
N/A
> Minor docs edits to legacy T1 token option
